### ISSUE TITLE
Proof of Concept Web App

### ISSUE THREAD

**Issue by antaranyan** [pouk/monocular#2]
Functional DICOM viewer demonstration for web and mobile learner interfaces. 

The DICOM viewer will exhibit designs and functions to include but not be limited to the following:

 - [ ] Image overview
 - [ ] H/F, R/L image orientation
 - [ ] Access and display of all images for a case
 - [x] Auto-fitting to different display resolutions
 - [ ] Image area magnifier
 - [ ] W/L Window / Level
 - [ ] Simple image annotation
 - [ ] Continuous zoom
 - [x] Pan
 - [ ] Hidden tool menus

**Comment by antaranyan** [comment]
### Square Rubble (Uncoursed) Masonry

![g4777](https://user-images.githubusercontent.com/25614707/62418223-af4d0500-b675-11e9-90c3-d3f50c4a1b3b.png)

**Comment by antaranyan** [comment]
### Service Workers

![image](https://user-images.githubusercontent.com/25614707/62424034-20260880-b6da-11e9-93e4-cf6b19f98b08.png)

- [Cookbook](https://serviceworke.rs/)
- [MDN - Guide](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers)
